name: Pipeline

on: [push]

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Unit Tests
        run: ./gradlew testDebugUnitTest

  android_tests:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedDebugAndroidTest

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: app/build/reports

  build:
    needs: [unit_tests, android_tests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

#      - name: Setup JDK 1.8
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8

      - name: Generate Debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: debug.apk
          path: app/build/outputs/apk/debug